baseURL = 'https://proteus.west-mimosa.ts.net/'
languageCode = 'en-gb'
title = 'Nerdy Day Trips Reborn'
theme = "ndt2"
enableRobotsTXT = true
enableGitInfo = true

relativeURLs = true

[Permalinks]
    daytrip = "/:slug/"
    post = "/blog/:year/:month/:filename/"

[outputs]
    section = ['html', 'rss', 'json']
    home = ['html', 'rss']
    page = ['html']
    rss = ['rss']
    taxonomy = ['html', 'rss']
    term = ['html', 'rss']

[markup.goldmark.renderer]
    unsafe = true

[params]
    mainSections = ["daytrip", "post"]
    description = "A global map of places to visit that might appeal to nerdy types"

[menu]
  [[menu.main]]
    name = "Map"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40
