name: Bug Report
description: File a bug report for the Nerdy Day Trips website.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: Device Type
      description: What type of device were you using? (e.g., Desktop, iPhone 13, Android Tablet)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What is the OS and version? (e.g., Windows 11, macOS Sonoma 14.4, iOS 17.3, Android 14)
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: What browser and version were you using? (e.g., Chrome 123, Safari 17.2, Firefox 125)
    validations:
      required: false
